### ISSUE TITLE
add a "Data" tab and maybe a "Resources" tab

### ISSUE THREAD

**Issue by ryanpeek** [SCCWRP/CABW2018_R_training#5]
Just a reminder to do this...I can add this later. It was nice having a data tab so it's easy for folks to locate and download the data if they get lost or behind....similarly it's nice pulling out some good R resources for folks to peruse after the workshop.

See here as example:
https://gge-ucd.github.io/R-DAVIS/resources.html

**Comment by fawda123** [comment]
Added in #7
